"""Add competencies_skipped field to SetupWizardData

Revision ID: c6193f525e19
Revises: 07e0d62e2b5f
Create Date: 2025-10-18 10:15:03.377617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6193f525e19'
down_revision = '07e0d62e2b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first with default value False
    op.add_column('setup_wizard_data', sa.Column('competencies_skipped', sa.Boolean(), nullable=True, server_default=sa.false()))
    # Update existing rows to have False value
    op.execute('UPDATE setup_wizard_data SET competencies_skipped = FALSE WHERE competencies_skipped IS NULL')
    # Now make it NOT NULL - use batch mode for SQLite compatibility
    with op.batch_alter_table('setup_wizard_data', schema=None) as batch_op:
        batch_op.alter_column('competencies_skipped', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setup_wizard_data', 'competencies_skipped')
    # ### end Alembic commands ###
